vich_uploader:
    db_driver: orm

    mappings:
        post_images:
            uri_prefix:         '%app.path.post_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.post_images%'
            
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
